[workspace]
resolver = "2"
members = [
    "create_fine_tuning_job",
    "list_fine_tuning_jobs",
    "retrieve_fine_tuning_job",
    "cancel_fine_tuning_job",
    "list_fine_tuning_job_events",
    "list_fine_tuning_checkpoints",
]
